apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-alerts
data:
 alertmanager.yml: |
   global:
     smtp_smarthost: 'smtp.delta.com:25'
     smtp_from: 'PrometheusAlerts@delta.com'
   route:
     receiver: all
     #group_by: []
     group_wait: 30s
     group_interval: 10s
     repeat_interval: 10s
     #continue: true
   receivers:
   - name: mail
     email_configs:
     - to: "satabdi.das@delta.com"
   - name: all
     email_configs:
     - to: "satabdi.das@delta.com"
     webhook_configs:
     - url: http://alertmanager:9093/api/v1/alerts
