apiVersion: v1
data:
 alertmanager.yml: |
   global:
     smtp_smarthost: 'smtp.delta.com:25'
     smtp_from: 'PrometheusAlerts@delta.com'
   route:
     receiver: all
     group_by: []
   receivers:
   - name: alert-buffer-wh
     webhook_configs:
     - url: http://localhost:9099/topics/alerts
   - name: mail
     email_configs:
     - to: "satabdi.das@delta.com"
   - name: all
     email_configs:
     - to: "satabdi.das@delta.com"
     webhook_configs:
     - url: http://localhost:9099/topics/alerts
kind: ConfigMap
metadata:
 creationTimestamp: null
 name: prometheus-alerts
