apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-k8s
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s
    scrape_configs:    
    - job_name: 'prometheus'
      static_configs:
         - targets: ['localhost:9090']         
    - job_name: 'demoapplication'
      static_configs:
         - targets: ['restservice:8080']         
    - job_name: 'demoapplication'
      static_configs:
         - targets: ['cadvisor:8080']
