apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  fortAlert.rules: |-
   groups:
   - name: example
   rules:

   # Alert for any instance that is unreachable for >5 minutes.
   - alert: InstanceDown
    expr: up == 0
    for: 5m
