apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-monitoring
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-monitoring
  template:
    metadata:
      name: prometheus-monitoring
      labels:
        app: prometheus-monitoring
    spec:
      containers:
      # Prometheus server
      - name: prometheus
        image: prom/prometheus:v1.3.1
        args:
          - '-storage.local.retention=72h'
          - '-storage.local.path=/home'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-alertmanager.url=http://localhost:9093'
          - '-web.external-url=https://evila570.delta.com/prometheus'
          - '-web.route-prefix=/prometheus'
        ports:
        - name: web
          containerPort: 9090
        resources:
          limits:
            cpu: 12000m
            memory: 10000Mi
          requests:
            cpu: 4000m
            memory: 4000Mi
